version: "2"

run:
  timeout: 5m
  build-tags:
    - integration

linters:
  # Run with all default linters enabled and in addition the linters listed below.
  enable:
    - bodyclose
    # - copyloopvar
    - errorlint
    - gosec
    - makezero
    - paralleltest
    - revive
    - unconvert
    - unparam
    - wastedassign
  settings:
    paralleltest:
      ignore-missing-subtests: true
  exclusions:
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - revive
          - unused
        path: (.+)_test.go
        text: ^(unused-parameter)|(.*is unused)

      - linters:
          - revive
        path: "integration_tests"

      - linters:
          - paralleltest
        path: "integration_tests"

issues:
  max-same-issues: 0

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/astrocode-id/go-flaresolverr
